db:
  user: postgres
  password: admin
  host: localhost
  port: 5432
  schema: bank_db
spring:
  liquibase:
    change-log: classpath:/schema.xml
  jpa:
    database-platform: postgres
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.schema}
    password: ${db.password}
    username: ${db.user}

prefix-client:
  version: v2
  url: http://localhost:8082/${prefix-client.version}